GET  http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/657b94cc719c7f0c773e2b76

###

DELETE  http://localhost:3001/api/persons/657b94cc719c7f0c773e2b76

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas 4",
    "number": "040-123456"
}

###

PUT http://localhost:3001/api/persons/657b94cc719c7f0c773e2b76
content-type: application/json

{
    "number": "000-0000"
}